build(docker): 更新镜像构建流程以包含版本号
- 在构建和保存 Docker 镜像时添加了获取和使用最新版本号的步骤
- 修改了镜像名称以包含版本号，例如：masx200/docker-squash:1.2.3
- 更新了文件名以反映版本号，例如：docker-squash-1.2.3.image.tgz
- 增加了错误检查以确保成功获取版本号

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -32,7 +32,17 @@ jobs:
       - run: mkdir -p ./dist
       - run: docker images
       - name: Build and save
-        run: docker save masx200/docker-squash:latest | gzip > ./dist/masx200-docker-squash-latest-image.tgz
+        run: |
+          VERSION=$(curl -s https://pypi.org/pypi/$PACKAGE_NAME/json | jq -r '.info.version')
+
+          # 检查是否成功获取版本号
+          if [ -z "$VERSION" ]; then
+              echo "Failed to fetch version for package: $PACKAGE_NAME"
+              exit 1
+          else
+              echo "The latest version of $PACKAGE_NAME is $VERSION"
+          fi
+          docker save masx200/docker-squash:$VERSION | gzip > ./dist/masx200-docker-squash-$VERSION-image.tgz
 
       - name: Release
         uses: softprops/action-gh-release@v2
